plugins:
  - artifactId: ace-editor
  - artifactId: antisamy-markup-formatter
  - artifactId: apache-httpcomponents-client-4-api
  - artifactId: bootstrap4-api
  - artifactId: bouncycastle-api
  - artifactId: branch-api
  - artifactId: build-timeout
  - artifactId: checks-api
  - artifactId: cloudbees-folder
  - artifactId: command-launcher
  - artifactId: configuration-as-code
  - artifactId: credentials
  - artifactId: credentials-binding
  - artifactId: display-url-api
  - artifactId: durable-task
  - artifactId: echarts-api
  - artifactId: email-ext
  - artifactId: font-awesome-api
  - artifactId: git
  - artifactId: git-client
  - artifactId: git-server
  - artifactId: github
  - artifactId: github-api
  - artifactId: github-branch-source
  - artifactId: handlebars
  - artifactId: jackson2-api
  - artifactId: jaxb
  - artifactId: jdk-tool
  - artifactId: jquery3-api
  - artifactId: jsch
  - artifactId: junit
  - artifactId: ldap
  - artifactId: lockable-resources
  - artifactId: mailer
  - artifactId: matrix-auth
  - artifactId: matrix-project
  - artifactId: momentjs
  - artifactId: okhttp-api
  - artifactId: pam-auth
  - artifactId: pipeline-build-step
  - artifactId: pipeline-github-lib
  - artifactId: pipeline-graph-analysis
  - artifactId: pipeline-input-step
  - artifactId: pipeline-milestone-step
  - artifactId: pipeline-model-api
  - artifactId: pipeline-model-definition
  - artifactId: pipeline-model-extensions
  - artifactId: pipeline-rest-api
  - artifactId: pipeline-stage-step
  - artifactId: pipeline-stage-tags-metadata
  - artifactId: pipeline-stage-view
  - artifactId: pipeline-utility-steps
  - artifactId: plain-credentials
  - artifactId: plugin-util-api
  - artifactId: popper-api
  - artifactId: resource-disposer
  - artifactId: scm-api
  - artifactId: script-security
  - artifactId: snakeyaml-api
  - artifactId: ssh-credentials
  - artifactId: ssh-slaves
  - artifactId: structs
  - artifactId: timestamper
  - artifactId: token-macro
  - artifactId: trilead-api
  - artifactId: workflow-aggregator
  - artifactId: workflow-api
  - artifactId: workflow-basic-steps
  - artifactId: workflow-cps
  - artifactId: workflow-cps-global-lib
  - artifactId: workflow-durable-task-step
  - artifactId: workflow-job
  - artifactId: workflow-multibranch
  - artifactId: workflow-scm-step
  - artifactId: workflow-step-api
  - artifactId: workflow-support
  - artifactId: ws-cleanup
  - artifactId: snyk-security-scanner  